### PR TITLE
Winter17 update

### PR DESCRIPTION
**Pull request by sipiseppala**
A major update because I've spent a lot of time in the guild room lately and I'm not happy with the tikscreen:
* Fetch bus stop times from the new HSL API (Digitransit). **API keys are no longer needed so you can delete hslaccount.json file**
* Display bus times of four stops (Alvar Aallon puisto & Kemisti in both directions) in one list with destination of each bus showing.
* Some UI tweaks to Sodexo menu and guild events (got rid of red labels, now cool teal&orange like theme)
* Refactored a lot of old stuff out and made screen_client.js cleaner

Merry christmas!
-Sipi

### CODE REVIEW

**Comment by kryptidikettu** [comment]
Got any cool screenshots for us?

**Comment by Maindii** [comment]
http://i.imgur.com/n3rS4sT.png

Looks good!

**Comment by sipiseppala** [comment]
Merry Christmas:

photo111422056388735104

**Comment by kryptidikettu** [comment]
Nice! Merry 🎄!

**Pull request merged**
