### PR TITLE
Display the menu based on the time to of the day

### PR DESCRIPTION
**Pull request by Earlo**
After Sodexo at Ttalo closes Alvari menu will be show.
After Alvari closes Dipoli menu will be shown.

### CODE REVIEW

**Review by sipiseppala — CHANGES_REQUESTED** [review]
Restaurant URLs are not accessible from loadMenu(), maybe pass them as parameters or put in global variables?  

Also the "NO OPEN RESTAURANTS ;-;" should be put in an else-clause (now shows up every time)

**Comment by Earlo** [comment]
Ah, thanks for pointing these out.
Fixed these errors.

**Review by sipiseppala — CHANGES_REQUESTED** [review]
There's still typos in JSON parsing in loadAlvariDipoli():
menusfordays -> MenusForDays
setMenus -> SetMenus

You really should test these yourself before committing a pull request ;)

**Review by sipiseppala — COMMENTED** [review]
Alvari's time conditionals don't still seem to be quite correct,  
" mins < 15 " would mean that e.g. 15:30 is false (hours match but mins do not) and therefore only dipoli shows up.

Please, test before you commit ;)

**Review by sipiseppala — APPROVED** [review]
Excellent!

**Pull request merged**
